name: .NET Framework Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PersonnummerValidering.sln

    - name: Build solution
      run: msbuild PersonnummerValidering.sln /p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe PersonnummerValideringTest\bin\Release\PersonnummerValideringTest.dll
